let dadesApp=null;let perfilActual='avi_joan';
document.addEventListener('DOMContentLoaded',()=>{carregarDades();renderitzarInici();renderitzarContactes();renderitzarUrgencies();renderitzarMedicacio();renderitzarGraella();renderitzarConfiguracio();});
function canviarVista(v){document.querySelectorAll('.vista').forEach(x=>x.classList.remove('activa'));document.getElementById('vista-'+v).classList.add('activa');document.querySelectorAll('.tab-nav').forEach(b=>b.classList.toggle('actiu',b.dataset.vista===v));if(v==='configuracio')renderitzarConfiguracio();}
function carregarDades(){const d=Emmagatzematge.carregar();if(d){dadesApp=d;perfilActual=detectarPerfil(d);}else{dadesApp=JSON.parse(JSON.stringify(DADES_INICIALS));Emmagatzematge.guardar(dadesApp);}}
function detectarPerfil(d){if(!d.pacient||!d.pacient.nom)return'buida';if(d.pacient.nom.includes('Joan')&&d.pacient.telefon)return'avi_joan';return'buida';}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function seccioConfigurable(t,c){return'<details class="seccio-config" open><summary>'+esc(t)+'</summary><div class="contingut-seccio">'+c+'</div></details>';}

const ICONS={
  phone:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07 19.5 19.5 0 01-6-6 19.79 19.79 0 01-3.07-8.67A2 2 0 014.11 2h3a2 2 0 012 1.72 12.84 12.84 0 00.7 2.81 2 2 0 01-.45 2.11L8.09 9.91a16 16 0 006 6l1.27-1.27a2 2 0 012.11-.45 12.84 12.84 0 002.81.7A2 2 0 0122 16.92z"/></svg>',
  save:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><path d="M19 21H5a2 2 0 01-2-2V5a2 2 0 012-2h11l5 5v11a2 2 0 01-2 2z"/><polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/></svg>',
  download:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>',
  upload:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>',
  clipboard:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><path d="M16 4h2a2 2 0 012 2v14a2 2 0 01-2 2H6a2 2 0 01-2-2V6a2 2 0 012-2h2"/><rect x="8" y="2" width="8" height="4" rx="1" ry="1"/></svg>',
  trash:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2"/></svg>',
  user:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>',
  check:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><polyline points="20 6 9 17 4 12"/></svg>',
  shop:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><path d="M6 2L3 6v14a2 2 0 002 2h14a2 2 0 002-2V6l-3-4z"/><line x1="3" y1="6" x2="21" y2="6"/><path d="M16 10a4 4 0 01-8 0"/></svg>',
  video:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><path d="M23 7l-7 5 7 5V7z"/><rect x="1" y="5" width="15" height="14" rx="2" ry="2"/></svg>',
};

function netejarTel(t){return t.replace(/[\s\-]/g,'')}

function renderitzarInici(){if(!dadesApp)return;const p=dadesApp.pacient;document.getElementById('nom-pacient').textContent=p.nom;document.getElementById('estat-pacient').textContent=p.situacio;const tel=p.telefon&&!p.telefon.includes('PENDENT')?netejarTel(p.telefon):null;if(tel)document.getElementById('tel-pacient').innerHTML='<a href="tel:'+tel+'" class="btn-trucar">'+ICONS.phone+' Trucar al pacient</a>';else document.getElementById('tel-pacient').innerHTML='';const avisos=[];if(dadesApp.contactes_medics.some(c=>c.nom.includes('PENDENT')||!c.nom))avisos.push('Contactes mèdics pendents');if(dadesApp.voluntats_anticipades.existeix.includes('PENDENT')||!dadesApp.voluntats_anticipades.existeix)avisos.push('DVA pendent de verificar');if(dadesApp.medicacio.some(m=>m.dosi.includes('PENDENT')||!m.dosi))avisos.push('Medicació pendent de revisar');if(dadesApp.proveidors&&dadesApp.proveidors.some(p=>p.telefon.includes('PENDENT')||!p.telefon))avisos.push('Proveïdors pendents de contactar');if(!p.nom)avisos.push('Dades del pacient buides');document.getElementById('llista-avisos').innerHTML=avisos.length?avisos.map(a=>'<li class="aviso-item">'+a+'</li>').join(''):'<li class="aviso-item ok">Tot en ordre</li>';}
function renderitzarContactes(){if(!dadesApp)return;
  document.getElementById('llista-contactes-medics').innerHTML=dadesApp.contactes_medics.map(c=>{const t=c.telefon&&!c.telefon.includes('PENDENT');const tn=t?netejarTel(c.telefon):'';return'<li class="contacte-item"><div class="contacte-info"><strong>'+c.rol+'</strong><p>'+c.nom+(c.telefon?' &mdash; '+c.telefon:'')+'</p><small>'+c.notes+'</small></div><div>'+(t?'<div class="btn-grup"><a href="tel:'+tn+'" class="btn-trucar">'+ICONS.phone+'</a><a href="facetime:'+tn+'" class="btn-facetime">'+ICONS.video+'</a></div>':'<span class="pendent">PENDENT</span>')+'</div></li>';}).join('');
  const prov=dadesApp.proveidors||[];document.getElementById('llista-proveidors').innerHTML=prov.length?prov.map(p=>{const t=p.telefon&&!p.telefon.includes('PENDENT');const tn=t?netejarTel(p.telefon):'';return'<li class="contacte-item"><div class="contacte-info"><strong>'+p.nom+'</strong>'+(p.notes?'<small>'+p.notes+'</small>':'')+'</div><div>'+(t?'<div class="btn-grup"><a href="tel:'+tn+'" class="btn-trucar">'+ICONS.phone+'</a><a href="facetime:'+tn+'" class="btn-facetime">'+ICONS.video+'</a></div>':'<span class="pendent">PENDENT</span>')+'</div></li>';}).join(''):'<li style="padding:.5rem;color:#999">Cap proveïdor configurat</li>';
  document.getElementById('llista-rols-familiars').innerHTML=dadesApp.rols_familiars.map(r=>{const t=r.telefon&&!r.telefon.includes('PENDENT');const tn=t?netejarTel(r.telefon):'';return'<li class="contacte-item"><div class="contacte-info"><strong>'+r.rol+'</strong><p>'+r.principal+(r.suplent?' (+ '+r.suplent+')':'')+'</p><small>'+r.notes+'</small></div><div>'+(t?'<div class="btn-grup"><a href="tel:'+tn+'" class="btn-trucar">'+ICONS.phone+'</a><a href="facetime:'+tn+'" class="btn-facetime">'+ICONS.video+'</a></div>':'')+'</div></li>';}).join('');}
function renderitzarUrgencies(){if(!dadesApp)return;document.getElementById('contenidor-urgencies').innerHTML=dadesApp.protocols_urgencies.map((p,i)=>{const cls=p.greu?'targeta-urgencia-greu':'targeta-urgencia';const boto=p.greu?'<a href="tel:112" class="btn-trucar-emergencia">TRUCAR 112</a>':'';return'<div class="'+cls+'"><h3>'+(i+1)+'. '+p.situacio+'</h3><ol class="passos-urgencia"><li>'+p.pas1+'</li><li>'+p.pas2+'</li></ol><p><strong>Responsable:</strong> '+p.responsable+'</p><div>'+boto+'</div></div>';}).join('');}
function renderitzarMedicacio(){if(!dadesApp)return;document.getElementById('contenidor-medicacio').innerHTML=dadesApp.medicacio.map(m=>'<div class="item-medicacio"><h3>'+m.nom+' <small>'+m.via+'</small></h3><p><strong>Dosi:</strong> '+m.dosi+'</p><p><strong>Horari:</strong> '+m.horari+'</p><p><strong>Per a què:</strong> '+m.per_a_que+'</p>'+(m.notes.includes('NOMÉS')?'<p class="alerta-medicacio">'+m.notes+'</p>':'<small>'+m.notes+'</small>')+'</div>').join('');}
function renderitzarGraella(){if(!dadesApp)return;document.getElementById('contenidor-graella').innerHTML=Calendari.generarGraellaHTML(dadesApp,document.getElementById('escenari').value);}
function mostrarGraella(){renderitzarGraella();}
function exportarDades(){Emmagatzematge.exportar(dadesApp,'cuida-'+dadesApp.pacient.nom.toLowerCase()+'-'+new Date().toISOString().split('T')[0]+'.json');}
function importarDades(){Emmagatzematge.importar(d=>{if(confirm('Importar dades de '+(d.pacient?.nom||'desconegut')+'?')){dadesApp=d;perfilActual=detectarPerfil(d);Emmagatzematge.guardar(d);renderitzarInici();renderitzarContactes();renderitzarUrgencies();renderitzarMedicacio();renderitzarGraella();renderitzarConfiguracio();}});}
function canviarPerfil(p){if(!confirm('Canviar a «'+(p==='buida'?'Plantilla buida':'Avi Joan')+'»? Es perdran els canvis no guardats.'))return;const src=PERFILS[p];if(!src)return;dadesApp=JSON.parse(JSON.stringify(src));perfilActual=p;Emmagatzematge.guardar(dadesApp);renderitzarInici();renderitzarContactes();renderitzarUrgencies();renderitzarMedicacio();renderitzarGraella();renderitzarConfiguracio();}

function guardarConfiguracio(){const d=dadesApp;
  d.pacient.nom=document.getElementById('cfg-pacient-nom')?.value||'';d.pacient.situacio=document.getElementById('cfg-pacient-situacio')?.value||'';d.pacient.nota=document.getElementById('cfg-pacient-nota')?.value||'';d.pacient.telefon=document.getElementById('cfg-pacient-telefon')?.value||'';
  d.contactes_medics.forEach((c,i)=>{const el=document.getElementById('cfg-contacte-'+i);if(!el)return;c.rol=el.querySelector('.f-rol')?.value||c.rol;c.nom=el.querySelector('.f-nom')?.value||c.nom;c.telefon=el.querySelector('.f-tel')?.value||c.telefon;c.notes=el.querySelector('.f-notes')?.value||c.notes;c.prioritat=el.querySelector('.f-prioritat')?.value||c.prioritat;});
  d.rols_familiars.forEach((r,i)=>{const el=document.getElementById('cfg-rol-'+i);if(!el)return;r.rol=el.querySelector('.f-rol')?.value||r.rol;r.principal=el.querySelector('.f-principal')?.value||r.principal;r.suplent=el.querySelector('.f-suplent')?.value||r.suplent;r.telefon=el.querySelector('.f-tel')?.value||r.telefon;r.notes=el.querySelector('.f-notes')?.value||r.notes;});
  d.medicacio.forEach((m,i)=>{const el=document.getElementById('cfg-med-'+i);if(!el)return;m.nom=el.querySelector('.f-nom')?.value||m.nom;m.dosi=el.querySelector('.f-dosi')?.value||m.dosi;m.horari=el.querySelector('.f-horari')?.value||m.horari;m.via=el.querySelector('.f-via')?.value||m.via;m.per_a_que=el.querySelector('.f-perque')?.value||m.per_a_que;m.notes=el.querySelector('.f-notes')?.value||m.notes;});
  d.protocols_urgencies.forEach((p,i)=>{const el=document.getElementById('cfg-protocol-'+i);if(!el)return;p.situacio=el.querySelector('.f-situacio')?.value||p.situacio;p.pas1=el.querySelector('.f-pas1')?.value||p.pas1;p.pas2=el.querySelector('.f-pas2')?.value||p.pas2;p.responsable=el.querySelector('.f-responsable')?.value||p.responsable;p.greu=el.querySelector('.f-greu')?.checked||!1;const tel=el.querySelector('.f-tel')?.value;if(tel)p.tel=tel;});
  (d.proveidors||[]).forEach((p,i)=>{const el=document.getElementById('cfg-prov-'+i);if(!el)return;p.nom=el.querySelector('.f-nom')?.value||p.nom;p.telefon=el.querySelector('.f-tel')?.value||p.telefon;p.notes=el.querySelector('.f-notes')?.value||p.notes;});
  d.indicadors_desgast=[];document.querySelectorAll('#cfg-indicadors-llista .f-indicador').forEach(el=>{if(el.value.trim())d.indicadors_desgast.push(el.value.trim());});if(!d.indicadors_desgast.length)d.indicadors_desgast=[''];
  d.voluntats_anticipades.existeix=document.getElementById('cfg-dva-existeix')?.value||'';d.voluntats_anticipades.on_esta=document.getElementById('cfg-dva-on')?.value||'';
  d.pla_avia.principi=document.getElementById('cfg-avia-principi')?.value||'';d.pla_avia.contacte=document.getElementById('cfg-avia-contacte')?.value||'';
  d.graella.fase=document.getElementById('cfg-graella-fase')?.value||'';d.graella.escenari=document.getElementById('cfg-graella-escenari')?.value||'A';d.graella.cuidadora=document.getElementById('cfg-graella-cuidadora')?.value||'';d.graella.ical=document.getElementById('cfg-graella-ical')?.value||'';
  Emmagatzematge.guardar(dadesApp);renderitzarInici();renderitzarContactes();renderitzarUrgencies();renderitzarMedicacio();renderitzarGraella();alert(ICONS.check+' Dades guardades');}

function renderitzarConfiguracio(){const d=dadesApp;let h='';
  h+='<div class="selector-perfil"><button class="btn-perfil'+(perfilActual==='buida'?' actiu':'')+'" onclick="canviarPerfil(\'buida\')">'+ICONS.clipboard+' Plantilla buida</button><button class="btn-perfil'+(perfilActual==='avi_joan'?' actiu':'')+'" onclick="canviarPerfil(\'avi_joan\')">'+ICONS.user+' Avi Joan</button></div>';
  h+='<button class="btn-guardar" onclick="guardarConfiguracio()">'+ICONS.save+' Guardar tot</button>';
  h+=seccioConfigurable('Dades del pacient','<label class="camp-form">Nom <input id="cfg-pacient-nom" value="'+esc(d.pacient.nom)+'"></label><label class="camp-form">Situació <input id="cfg-pacient-situacio" value="'+esc(d.pacient.situacio)+'"></label><label class="camp-form">Telèfon <input id="cfg-pacient-telefon" value="'+esc(d.pacient.telefon||'')+'" type="tel"></label><label class="camp-form">Nota <textarea id="cfg-pacient-nota">'+esc(d.pacient.nota)+'</textarea></label><details class="pdf-paste"><summary>'+ICONS.clipboard+' Enganxa del PDF</summary><textarea placeholder="Enganxa aquí el text del PDF..."></textarea></details>');
  h+=seccioConfigurable('Contactes mèdics ('+d.contactes_medics.length+')','<div id="cfg-contactes-llista">'+d.contactes_medics.map((c,i)=>renderContacteForm(c,i)).join('')+'</div><button class="btn-afegir" onclick="afegirContacte()">+ Afegir contacte</button><details class="pdf-paste"><summary>'+ICONS.clipboard+' Enganxa del PDF</summary><textarea placeholder="Enganxa aquí els contactes del PDF..."></textarea></details>');
  h+=seccioConfigurable('Proveïdors ('+(d.proveidors||[]).length+')','<div id="cfg-proveidors-llista">'+(d.proveidors||[]).map((p,i)=>renderProveidorForm(p,i)).join('')+'</div><button class="btn-afegir" onclick="afegirProveidor()">+ Afegir proveïdor</button>');
  h+=seccioConfigurable('Rols familiars ('+d.rols_familiars.length+')','<div id="cfg-rols-llista">'+d.rols_familiars.map((r,i)=>renderRolForm(r,i)).join('')+'</div><button class="btn-afegir" onclick="afegirRol()">+ Afegir rol</button>');
  h+=seccioConfigurable('Medicació ('+d.medicacio.length+')','<div id="cfg-medicacio-llista">'+d.medicacio.map((m,i)=>renderMedicacioForm(m,i)).join('')+'</div><button class="btn-afegir" onclick="afegirMedicacio()">+ Afegir medicament</button><details class="pdf-paste"><summary>'+ICONS.clipboard+' Enganxa del PDF</summary><textarea placeholder="Enganxa aquí la pauta de medicació del PDF..."></textarea></details>');
  h+=seccioConfigurable('Voluntats anticipades (DVA)','<label class="camp-form">Existeix document? <input id="cfg-dva-existeix" value="'+esc(d.voluntats_anticipades.existeix)+'" placeholder="Sí / No / PENDENT"></label><label class="camp-form">On està? <textarea id="cfg-dva-on" placeholder="Ubicació del document...">'+esc(d.voluntats_anticipades.on_esta)+'</textarea></label>');
  h+=seccioConfigurable("Protocols d'urgència ("+d.protocols_urgencies.length+")",'<div id="cfg-protocols-llista">'+d.protocols_urgencies.map((p,i)=>renderProtocolForm(p,i)).join('')+'</div><button class="btn-afegir" onclick="afegirProtocol()">+ Afegir protocol</button>');
  h+=seccioConfigurable("Pla de l'àvia",'<label class="camp-form">Principi <input id="cfg-avia-principi" value="'+esc(d.pla_avia.principi)+'"></label><label class="camp-form">Contacte <input id="cfg-avia-contacte" value="'+esc(d.pla_avia.contacte)+'"></label>');
  h+=seccioConfigurable('Indicadors de desgast ('+d.indicadors_desgast.length+')','<div id="cfg-indicadors-llista">'+d.indicadors_desgast.map((ind,i)=>renderIndicadorForm(ind,i)).join('')+'</div><button class="btn-afegir" onclick="afegirIndicador()">+ Afegir indicador</button>');
  h+=seccioConfigurable('Graella setmanal','<label class="camp-form">Fase <input id="cfg-graella-fase" value="'+esc(d.graella.fase)+'" placeholder="crítica / estable"></label><label class="camp-form">Escenari <select id="cfg-graella-escenari"><option value="A"'+(d.graella.escenari==='A'?' selected':'')+'>A</option><option value="B"'+(d.graella.escenari==='B'?' selected':'')+'>B</option></select></label><label class="camp-form">Cuidadora <input id="cfg-graella-cuidadora" value="'+esc(d.graella.cuidadora)+'" placeholder="3h matí + 3h tarda (dl-ds)"></label><label class="camp-form">Enllaç calendari iCal <input id="cfg-graella-ical" value="'+esc(d.graella.ical||'')+'" placeholder="https://...ics"></label>');
  h+='<button class="btn-guardar" onclick="guardarConfiguracio()">'+ICONS.save+' Guardar tot</button>';
  document.getElementById('contingut-configuracio').innerHTML=h;}

function renderContacteForm(c,i){return'<div class="item-llista-config" id="cfg-contacte-'+i+'"><div class="capsalera-item"><strong>'+esc(c.rol||'Contacte')+'</strong><button class="btn-eliminar" onclick="eliminarContacte('+i+')">'+ICONS.trash+'</button></div><label class="camp-form">Rol <input class="f-rol" value="'+esc(c.rol)+'"></label><label class="camp-form">Nom <input class="f-nom" value="'+esc(c.nom)+'"></label><label class="camp-form">Telèfon <input class="f-tel" value="'+esc(c.telefon)+'" type="tel"></label><label class="camp-form">Notes <textarea class="f-notes">'+esc(c.notes)+'</textarea></label><label class="camp-form">Prioritat <select class="f-prioritat"><option value="alta"'+(c.prioritat==='alta'?' selected':'')+'>Alta</option><option value="mitjana"'+(c.prioritat==='mitjana'?' selected':'')+'>Mitjana</option><option value="baixa"'+(c.prioritat==='baixa'?' selected':'')+'>Baixa</option></select></label></div>';}
function renderProveidorForm(p,i){return'<div class="item-llista-config" id="cfg-prov-'+i+'"><div class="capsalera-item"><strong>'+esc(p.nom||'Proveïdor')+'</strong><button class="btn-eliminar" onclick="eliminarProveidor('+i+')">'+ICONS.trash+'</button></div><label class="camp-form">Nom <input class="f-nom" value="'+esc(p.nom)+'"></label><label class="camp-form">Telèfon <input class="f-tel" value="'+esc(p.telefon)+'" type="tel"></label><label class="camp-form">Notes <textarea class="f-notes">'+esc(p.notes)+'</textarea></label></div>';}
function renderRolForm(r,i){return'<div class="item-llista-config" id="cfg-rol-'+i+'"><div class="capsalera-item"><strong>'+esc(r.rol||'Rol')+'</strong><button class="btn-eliminar" onclick="eliminarRol('+i+')">'+ICONS.trash+'</button></div><label class="camp-form">Rol <input class="f-rol" value="'+esc(r.rol)+'"></label><label class="camp-form">Principal <input class="f-principal" value="'+esc(r.principal)+'"></label><label class="camp-form">Suplent <input class="f-suplent" value="'+esc(r.suplent)+'"></label><label class="camp-form">Telèfon <input class="f-tel" value="'+esc(r.telefon||'')+'" type="tel"></label><label class="camp-form">Notes <textarea class="f-notes">'+esc(r.notes)+'</textarea></label></div>';}
function renderMedicacioForm(m,i){return'<div class="item-llista-config" id="cfg-med-'+i+'"><div class="capsalera-item"><strong>'+esc(m.nom||'Medicament')+'</strong><button class="btn-eliminar" onclick="eliminarMedicacio('+i+')">'+ICONS.trash+'</button></div><label class="camp-form">Nom <input class="f-nom" value="'+esc(m.nom)+'"></label><label class="camp-form">Dosi <input class="f-dosi" value="'+esc(m.dosi)+'"></label><label class="camp-form">Horari <input class="f-horari" value="'+esc(m.horari)+'"></label><label class="camp-form">Via <input class="f-via" value="'+esc(m.via)+'"></label><label class="camp-form">Per a què <input class="f-perque" value="'+esc(m.per_a_que)+'"></label><label class="camp-form">Notes <textarea class="f-notes">'+esc(m.notes)+'</textarea></label></div>';}
function renderProtocolForm(p,i){const g=p.greu||!1;return'<div class="item-llista-config" id="cfg-protocol-'+i+'"><div class="capsalera-item"><strong>'+esc(p.situacio||'Protocol')+'</strong><button class="btn-eliminar" onclick="eliminarProtocol('+i+')">'+ICONS.trash+'</button></div><label class="camp-form">Situació <input class="f-situacio" value="'+esc(p.situacio)+'"></label><label class="camp-form">Pas 1 <input class="f-pas1" value="'+esc(p.pas1)+'"></label><label class="camp-form">Pas 2 <input class="f-pas2" value="'+esc(p.pas2)+'"></label><label class="camp-form">Responsable <input class="f-responsable" value="'+esc(p.responsable)+'"></label><label class="camp-form"><input class="f-greu" type="checkbox"'+(g?' checked':'')+'> Greu (mostra botó 112)</label><label class="camp-form">Tel. emergència <input class="f-tel" value="'+esc(p.tel||'')+'" placeholder="112"></label></div>';}
function renderIndicadorForm(v,i){return'<div class="item-llista-config" id="cfg-indicador-'+i+'"><div class="capsalera-item"><strong>Indicador '+(i+1)+'</strong><button class="btn-eliminar" onclick="eliminarIndicador('+i+')">'+ICONS.trash+'</button></div><input class="f-indicador" style="width:100%;padding:.5rem;border:1px solid #ddd;border-radius:6px;font-size:.9rem" value="'+esc(v)+'"></div>';}

function afegirContacte(){dadesApp.contactes_medics.push({rol:'',nom:'',telefon:'',notes:'',prioritat:'mitjana'});renderitzarConfiguracio();}
function eliminarContacte(i){if(dadesApp.contactes_medics.length<=1)return;dadesApp.contactes_medics.splice(i,1);renderitzarConfiguracio();}
function afegirProveidor(){if(!dadesApp.proveidors)dadesApp.proveidors=[];dadesApp.proveidors.push({nom:'',telefon:'',notes:''});renderitzarConfiguracio();}
function eliminarProveidor(i){if(dadesApp.proveidors&&dadesApp.proveidors.length>1){dadesApp.proveidors.splice(i,1);renderitzarConfiguracio();}}
function afegirRol(){dadesApp.rols_familiars.push({rol:'',principal:'',suplent:'',telefon:'',notes:''});renderitzarConfiguracio();}
function eliminarRol(i){if(dadesApp.rols_familiars.length<=1)return;dadesApp.rols_familiars.splice(i,1);renderitzarConfiguracio();}
function afegirMedicacio(){dadesApp.medicacio.push({nom:'',dosi:'',horari:'',via:'',per_a_que:'',notes:''});renderitzarConfiguracio();}
function eliminarMedicacio(i){if(dadesApp.medicacio.length<=1)return;dadesApp.medicacio.splice(i,1);renderitzarConfiguracio();}
function afegirProtocol(){dadesApp.protocols_urgencies.push({situacio:'',pas1:'',pas2:'',responsable:'',greu:!1});renderitzarConfiguracio();}
function eliminarProtocol(i){if(dadesApp.protocols_urgencies.length<=1)return;dadesApp.protocols_urgencies.splice(i,1);renderitzarConfiguracio();}
function afegirIndicador(){dadesApp.indicadors_desgast.push('');renderitzarConfiguracio();}
function eliminarIndicador(i){if(dadesApp.indicadors_desgast.length<=1)return;dadesApp.indicadors_desgast.splice(i,1);renderitzarConfiguracio();}
