let dadesApp=null;
document.addEventListener('DOMContentLoaded',()=>{carregarDades();renderitzarInici();renderitzarContactes();renderitzarUrgencies();renderitzarMedicacio();renderitzarGraella();});
function canviarVista(v){document.querySelectorAll('.vista').forEach(x=>x.classList.remove('activa'));document.getElementById('vista-'+v).classList.add('activa');document.querySelectorAll('.tab-nav').forEach(b=>b.classList.toggle('actiu',b.dataset.vista===v));}
function carregarDades(){dadesApp=Emmagatzematge.carregar()||JSON.parse(JSON.stringify(DADES_INICIALS));if(!Emmagatzematge.carregar())Emmagatzematge.guardar(dadesApp);}
function renderitzarInici(){if(!dadesApp)return;document.getElementById('nom-pacient').textContent=dadesApp.pacient.nom;document.getElementById('estat-pacient').textContent=dadesApp.pacient.situacio;const avisos=[];if(dadesApp.contactes_medics.some(c=>c.nom.includes('PENDENT')))avisos.push('⚠️ Contactes mèdics pendents');if(dadesApp.voluntats_anticipades.existeix.includes('PENDENT'))avisos.push('⚠️ DVA pendent de verificar');if(dadesApp.medicacio.some(m=>m.dosi.includes('PENDENT')))avisos.push('⚠️ Medicació pendent de revisar');document.getElementById('llista-avisos').innerHTML=avisos.length?avisos.map(a=>'<li>'+a+'</li>').join(''):'<li>✅ Tot en ordre</li>';}
function renderitzarContactes(){if(!dadesApp)return;document.getElementById('llista-contactes-medics').innerHTML=dadesApp.contactes_medics.map(c=>{const t=c.telefon&&!c.telefon.includes('PENDENT');return'<li class="contacte-item"><div class="contacte-info"><strong>'+c.rol+'</strong><p>'+c.nom+(c.telefon?' — '+c.telefon:'')+'</p><small>'+c.notes+'</small></div><div>'+(t?'<a href="tel:'+c.telefon+'" class="btn-trucar">📞 Trucar</a>':'<span class="pendent">PENDENT</span>')+'</div></li>';}).join('');document.getElementById('llista-rols-familiars').innerHTML=dadesApp.rols_familiars.map(r=>'<li class="contacte-item"><strong>'+r.rol+'</strong><p>Principal: '+r.principal+' | Suplent: '+r.suplent+'</p><small>'+r.notes+'</small></li>').join('');}
function renderitzarUrgencies(){if(!dadesApp)return;document.getElementById('contenidor-urgencies').innerHTML=dadesApp.protocols_urgencies.map((p,i)=>{const cls=p.greu?'targeta-urgencia-greu':'targeta-urgencia';const boto=p.greu?'<a href="tel:112" class="btn-trucar-emergencia">🚨 TRUCAR 112</a>':'';return'<div class="'+cls+'"><h3>'+(i+1)+'. '+p.situacio+'</h3><ol class="passos-urgencia"><li>'+p.pas1+'</li><li>'+p.pas2+'</li></ol><p><strong>Responsable:</strong> '+p.responsable+'</p><div>'+boto+'</div></div>';}).join('');}
function renderitzarMedicacio(){if(!dadesApp)return;document.getElementById('contenidor-medicacio').innerHTML=dadesApp.medicacio.map(m=>'<div class="item-medicacio"><h3>'+m.nom+' <small>'+m.via+'</small></h3><p><strong>Dosi:</strong> '+m.dosi+'</p><p><strong>Horari:</strong> '+m.horari+'</p><p><strong>Per a què:</strong> '+m.per_a_que+'</p>'+(m.notes.includes('⚠️')?'<p class="alerta-medicacio">'+m.notes+'</p>':'<small>'+m.notes+'</small>')+'</div>').join('');}
function renderitzarGraella(){if(!dadesApp)return;document.getElementById('contenidor-graella').innerHTML=Calendari.generarGraellaHTML(dadesApp,document.getElementById('escenari').value);}
function mostrarGraella(){renderitzarGraella();}
function exportarDades(){Emmagatzematge.exportar(dadesApp,'cuida-'+dadesApp.pacient.nom.toLowerCase()+'-'+new Date().toISOString().split('T')[0]+'.json');}
function importarDades(){Emmagatzematge.importar(d=>{if(confirm('Importar dades de '+(d.pacient?.nom||'desconegut')+'?')){dadesApp=d;Emmagatzematge.guardar(d);renderitzarInici();renderitzarContactes();renderitzarUrgencies();renderitzarMedicacio();renderitzarGraella();}});}
