let dadesApp=null;let perfilActual='avi_joan';
document.addEventListener('DOMContentLoaded',()=>{carregarDades();renderitzarInici();renderitzarContactes();renderitzarUrgencies();renderitzarMedicacio();renderitzarGraella();renderitzarConfiguracio();});
function canviarVista(v){document.querySelectorAll('.vista').forEach(x=>x.classList.remove('activa'));document.getElementById('vista-'+v).classList.add('activa');document.querySelectorAll('.tab-nav').forEach(b=>b.classList.toggle('actiu',b.dataset.vista===v));if(v==='configuracio')renderitzarConfiguracio();}
function carregarDades(){dadesApp=JSON.parse(JSON.stringify(DADES_INICIALS));perfilActual='avi_joan';}
function detectarPerfil(d){if(!d.pacient||!d.pacient.nom)return'buida';if(d.pacient.nom.includes('Joan')&&d.pacient.telefon)return'avi_joan';return'buida';}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function seccioConfigurable(t,c){return'<details class="seccio-config" open><summary>'+esc(t)+'</summary><div class="contingut-seccio">'+c+'</div></details>';}

const ICONS={
  phone:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07 19.5 19.5 0 01-6-6 19.79 19.79 0 01-3.07-8.67A2 2 0 014.11 2h3a2 2 0 012 1.72 12.84 12.84 0 00.7 2.81 2 2 0 01-.45 2.11L8.09 9.91a16 16 0 006 6l1.27-1.27a2 2 0 012.11-.45 12.84 12.84 0 002.81.7A2 2 0 0122 16.92z"/></svg>',
  download:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>',
  upload:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>',
  user:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>',
  video:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icn-sm"><path d="M23 7l-7 5 7 5V7z"/><rect x="1" y="5" width="15" height="14" rx="2" ry="2"/></svg>',
};

function netejarTel(t){return t.replace(/[\s\-]/g,'')}

function renderitzarInici(){if(!dadesApp)return;const p=dadesApp.pacient;document.getElementById('nom-pacient').textContent=p.nom;document.getElementById('estat-pacient').textContent=p.situacio;const tel=p.telefon&&!p.telefon.includes('PENDENT')?netejarTel(p.telefon):null;document.getElementById('tel-pacient').innerHTML=tel?'<a href="tel:'+tel+'" class="btn-trucar">'+ICONS.phone+' Trucar al pacient</a>':'';const f=document.getElementById('pacient-foto');f.innerHTML=p.foto?'<img src="'+esc(p.foto)+'" alt="Foto del pacient" class="foto-pacient">':'<div class="foto-pacient-placeholder">'+ICONS.user+'</div>';const avisos=[];if(dadesApp.contactes_medics.some(c=>c.nom.includes('PENDENT')||!c.nom))avisos.push('Contactes mèdics pendents');if(dadesApp.voluntats_anticipades.existeix.includes('PENDENT')||!dadesApp.voluntats_anticipades.existeix)avisos.push('DVA pendent de verificar');if(dadesApp.medicacio.some(m=>m.dosi.includes('PENDENT')||!m.dosi))avisos.push('Medicació pendent de revisar');if(dadesApp.proveidors&&dadesApp.proveidors.some(p=>p.telefon.includes('PENDENT')||!p.telefon))avisos.push('Proveïdors pendents de contactar');if(!p.nom)avisos.push('Dades del pacient buides');document.getElementById('llista-avisos').innerHTML=avisos.length?avisos.map(a=>'<li class="aviso-item">'+a+'</li>').join(''):'<li class="aviso-item ok">Tot en ordre</li>';}
function renderitzarContactes(){if(!dadesApp)return;
  document.getElementById('llista-contactes-medics').innerHTML=dadesApp.contactes_medics.map(c=>{const t=c.telefon&&!c.telefon.includes('PENDENT');const tn=t?netejarTel(c.telefon):'';return'<li class="contacte-item"><div class="contacte-info"><strong>'+c.rol+'</strong><p>'+c.nom+(c.telefon?' &mdash; '+c.telefon:'')+'</p><small>'+c.notes+'</small></div><div>'+(t?'<div class="btn-grup"><a href="tel:'+tn+'" class="btn-trucar">'+ICONS.phone+'</a><a href="facetime:'+tn+'" class="btn-facetime">'+ICONS.video+'</a></div>':'<span class="pendent">PENDENT</span>')+'</div></li>';}).join('');
  const prov=dadesApp.proveidors||[];document.getElementById('llista-proveidors').innerHTML=prov.length?prov.map(p=>{const t=p.telefon&&!p.telefon.includes('PENDENT');const tn=t?netejarTel(p.telefon):'';return'<li class="contacte-item"><div class="contacte-info"><strong>'+p.nom+'</strong>'+(p.notes?'<small>'+p.notes+'</small>':'')+'</div><div>'+(t?'<div class="btn-grup"><a href="tel:'+tn+'" class="btn-trucar">'+ICONS.phone+'</a><a href="facetime:'+tn+'" class="btn-facetime">'+ICONS.video+'</a></div>':'<span class="pendent">PENDENT</span>')+'</div></li>';}).join(''):'<li style="padding:.5rem;color:#999">Cap proveïdor configurat</li>';
  document.getElementById('llista-rols-familiars').innerHTML=dadesApp.rols_familiars.map(r=>{const t=r.telefon&&!r.telefon.includes('PENDENT');const tn=t?netejarTel(r.telefon):'';return'<li class="contacte-item"><div class="contacte-info"><strong>'+r.rol+'</strong><p>'+r.principal+(r.suplent?' (+ '+r.suplent+')':'')+'</p><small>'+r.notes+'</small></div><div>'+(t?'<div class="btn-grup"><a href="tel:'+tn+'" class="btn-trucar">'+ICONS.phone+'</a><a href="facetime:'+tn+'" class="btn-facetime">'+ICONS.video+'</a></div>':'')+'</div></li>';}).join('');}
function renderitzarUrgencies(){if(!dadesApp)return;document.getElementById('contenidor-urgencies').innerHTML=dadesApp.protocols_urgencies.map((p,i)=>{const cls=p.greu?'targeta-urgencia-greu':'targeta-urgencia';const boto=p.greu?'<a href="tel:112" class="btn-trucar-emergencia">TRUCAR 112</a>':'';return'<div class="'+cls+'"><h3>'+(i+1)+'. '+p.situacio+'</h3><ol class="passos-urgencia"><li>'+p.pas1+'</li><li>'+p.pas2+'</li></ol><p><strong>Responsable:</strong> '+p.responsable+'</p><div>'+boto+'</div></div>';}).join('');}
function renderitzarMedicacio(){if(!dadesApp)return;document.getElementById('contenidor-medicacio').innerHTML=dadesApp.medicacio.map(m=>'<div class="item-medicacio"><h3>'+m.nom+' <small>'+m.via+'</small></h3><p><strong>Dosi:</strong> '+m.dosi+'</p><p><strong>Horari:</strong> '+m.horari+'</p><p><strong>Per a què:</strong> '+m.per_a_que+'</p>'+(m.notes.includes('NOMÉS')?'<p class="alerta-medicacio">'+m.notes+'</p>':'<small>'+m.notes+'</small>')+'</div>').join('');}
function renderitzarGraella(){if(!dadesApp)return;document.getElementById('contenidor-graella').innerHTML=Calendari.generarGraellaHTML(dadesApp,document.getElementById('escenari').value);}
function mostrarGraella(){renderitzarGraella();}
function exportarDades(){Emmagatzematge.exportar(dadesApp,'cuida-'+dadesApp.pacient.nom.toLowerCase()+'-'+new Date().toISOString().split('T')[0]+'.json');}
function importarDades(){Emmagatzematge.importar(d=>{if(confirm('Importar dades de '+(d.pacient?.nom||'desconegut')+'?')){dadesApp=d;perfilActual=detectarPerfil(d);Emmagatzematge.guardar(d);renderitzarInici();renderitzarContactes();renderitzarUrgencies();renderitzarMedicacio();renderitzarGraella();renderitzarConfiguracio();}});}
function canviarPerfil(p){if(!confirm('Canviar a «'+(p==='buida'?'Plantilla buida':'Avi Joan')+'»? Es perdran els canvis no guardats.'))return;const src=PERFILS[p];if(!src)return;dadesApp=JSON.parse(JSON.stringify(src));perfilActual=p;Emmagatzematge.guardar(dadesApp);renderitzarInici();renderitzarContactes();renderitzarUrgencies();renderitzarMedicacio();renderitzarGraella();renderitzarConfiguracio();}

function renderitzarConfiguracio(){const d=dadesApp;let h='';
  h+='<div class="selector-perfil"><button class="btn-perfil'+(perfilActual==='buida'?' actiu':'')+'" onclick="canviarPerfil(\'buida\')">'+ICONS.clipboard+' Plantilla buida</button><button class="btn-perfil'+(perfilActual==='avi_joan'?' actiu':'')+'" onclick="canviarPerfil(\'avi_joan\')">'+ICONS.user+' Avi Joan</button></div>';
  h+=seccioConfigurable('Com funciona Cuida','<p class="guia-intro">Les dades venen del repositori GitHub i són iguals per tothom. Per actualitzar-les cal editar <code>dades.js</code> al repositori i desplegar de nou.</p><div class="guia-item"><strong>Inici</strong> - Resum del pacient, avisos pendents i accions ràpides</div><div class="guia-item"><strong>Graella</strong> - Horari setmanal. Canvia entre escenari A i B</div><div class="guia-item"><strong>Contactes</strong> - Metges, proveïdors i família amb botons de trucada</div><div class="guia-item"><strong>Urgències</strong> - Protocols pas a pas. Botó vermell truca al 112</div><div class="guia-item"><strong>Medicació</strong> - Llista completa amb dosis, horaris i alertes</div><div class="guia-item"><strong>Config</strong> - Perfils, exportar/importar i informació</div>');
  h+=seccioConfigurable('Exportar / Importar','<p style="font-size:.8rem;color:#999;margin-bottom:.75rem">Per compartir les dades amb algú que tingui una versió modificada, pots exportar i importar fitxers JSON.</p><div style="display:flex;gap:.5rem"><button class="btn-secundari" onclick="exportarDades()">'+ICONS.download+' Exportar</button><button class="btn-secundari" onclick="importarDades()">'+ICONS.upload+' Importar</button></div>');
  document.getElementById('contingut-configuracio').innerHTML=h;}
